technical_seo:
  max_points: 80
  rules:
    meta_title_exists:
      description: Meta title er defineret
      data_key: meta_title_exists
      type: boolean_true
      points: 10
      fetcher: technical_fetchers
    meta_description_exists:
      description: Meta description er defineret
      data_key: meta_description_exists
      type: boolean_true
      points: 10
      fetcher: technical_fetchers
    has_h1:
      description: H1 tag er tilstede
      data_key: has_h1
      type: boolean_true
      points: 10
      fetcher: technical_fetchers
    has_robots_txt:
      description: robots.txt eksisterer
      data_key: has_robots_txt
      type: boolean_true
      points: 10
      fetcher: robots_sitemap_fetcher
    has_sitemap_xml:
      description: sitemap.xml eksisterer
      data_key: has_sitemap_xml
      type: boolean_true
      points: 10
      fetcher: robots_sitemap_fetcher
    mobile_friendly_score:
      description: Mobilvenlighedsscore
      data_key: mobile_score
      type: greater_than_or_equal
      threshold: 50
      points: 10
      fetcher: performance_fetcher
    desktop_score:
      description: Desktop performance score
      data_key: desktop_score
      type: greater_than_or_equal
      threshold: 50
      points: 10
      fetcher: performance_fetcher
    has_structured_data:
      description: Strukturerede data fundet
      data_key: has_structured_data
      type: boolean_true
      points: 10
      fetcher: technical_fetchers
security_trust:
  max_points: 40
  rules:
    cookie_notice_found:
      data_key: cookie_notice_found
      description: Der vises en tydelig cookie-notifikation ved første besøg.
      fetcher: privacy_fetchers
      points: 5
      type: boolean_true
    google_my_business_found:
      data_key: gmb_found
      description: Virksomheden er registreret og synlig på Google My Business.
      fetcher: gmb_fetcher
      points: 5
      type: boolean_true
    legal_info_found:
      data_key: legal_info_found
      description: Der fremgår kontaktoplysninger, CVR og anden lovpligtig information.
      fetcher: contact_fetchers
      points: 5
      type: boolean_true
    privacy_policy_found:
      data_key: privacy_policy_found
      description: Siden linker til en tydelig persondatapolitik.
      fetcher: privacy_fetchers
      points: 5
      type: boolean_true
    social_links_present:
      data_key: social_links_found
      description: Der er links til sociale medier.
      fetcher: social_fetchers
      points: 5
      type: boolean_true
    ssl_certificate:
      data_key: ssl_valid
      description: SSL-certifikatet er gyldigt og korrekt konfigureret.
      fetcher: technical_fetchers
      points: 10
      type: boolean_true
    trust_badges_present:
      data_key: trust_badges_found
      description: Siden viser troværdighedssymboler (e-mærket, Trustpilot mv.).
      fetcher: trust_signal_fetcher
      points: 5
      type: boolean_true
user_experience:
  max_points: 40
  rules:
    text_visibility_check:
      description: "Tekstkontrast og læsbarhed vurderes visuelt (f.eks. mørk tekst på lys baggrund)."
      data_key: has_visible_text
      fetcher: website_fetchers
      type: boolean_true
      points: 10

    no_autoplay_check:
      description: "Siden starter ikke videoer eller lyd automatisk ved besøg."
      data_key: has_autoplay
      fetcher: website_fetchers
      type: boolean_false
      points: 10

    custom_404_page_check:
      description: "Siden har en brugerdefineret 404-side, hvilket giver bedre brugeroplevelse ved fejl."
      data_key: has_custom_404
      fetcher: website_fetchers
      type: boolean_true
      points: 10

    domain_consistency_check:
      description: "Domænet viderestiller korrekt mellem www og uden www eller mellem http og https."
      data_key: domain_consistency
      fetcher: website_fetchers
      type: boolean_true
      points: 10
user_experience:
  max_points: 110
  rules:
    video_or_image_header_check:
      description: "Siden har et moderne visuelt udtryk med video eller stort hero-billede i toppen."
      data_key: has_hero_visual
      fetcher: image_fetchers
      type: boolean_true
      points: 10

    brand_color_consistency_check:
      description: "Siden bruger gennemgående farver, som matcher virksomhedens visuelle identitet."
      data_key: has_consistent_colors
      fetcher: website_fetchers
      type: boolean_true
      points: 10

    visible_cta_check:
      description: "Der er tydelige og klikbare Call-to-Actions (CTA) på siden."
      data_key: has_clear_cta
      fetcher: website_fetchers
      type: boolean_true
      points: 10

    trust_signals_check:
      description: "Siden viser trust-signaler som Trustpilot, e-mærket, Google Rating mv."
      data_key: trust_elements_count
      fetcher: trust_signal_fetcher
      type: greater_than_or_equal
      threshold: 1
      points: 10

    unique_value_proposition_check:
      description: "Der fremgår tydelig USP – f.eks. 'Prisgaranti', 'Levering i morgen', 'Bæredygtig produktion'."
      data_key: has_usp_keywords
      fetcher: website_fetchers
      type: boolean_true
      points: 10

    phone_number_on_page_check:
      description: "Der fremgår tydeligt telefonnummer, som kan bruges til kundeservice eller salg."
      data_key: phone_visible
      fetcher: contact_fetchers
      type: boolean_true
      points: 10

    email_address_on_page_check:
      description: "Der fremgår en e-mail-adresse, som kan bruges til kontakt."
      data_key: email_visible
      fetcher: contact_fetchers
      type: boolean_true
      points: 10

    opening_hours_visible_check:
      description: "Virksomhedens åbningstider er synlige og opdaterede på siden (evt. via GMB)."
      data_key: has_opening_hours
      fetcher: gmb_fetcher
      type: boolean_true
      points: 10

    newsletter_signup_check:
      description: "Siden tilbyder tilmelding til nyhedsbrev (f.eks. via popup, bundtekst eller sektion)."
      data_key: has_newsletter
      fetcher: form_fetcher
      type: boolean_true
      points: 10

    cookie_banner_present_check:
      description: "Der vises en cookie-besked ved første besøg, som lever op til GDPR."
      data_key: has_cookie_banner
      fetcher: privacy_fetchers
      type: boolean_true
      points: 10

    contact_form_present_check:
      description: "Der findes en kontaktformular på siden, hvor besøgende kan skrive direkte."
      data_key: has_contact_form
      fetcher: form_fetcher
      type: boolean_true
      points: 10