name: Share Vexto debug to Secret Gist

on:
  workflow_dispatch:  # manuel kørsel
  push:               # automatisk kørsel ved ændringer i disse paths
    branches: [ main ]
    paths:
      - "src/vexto/scoring/**"
      - "fetcher_diagnose_full.py"
      - "config/scoring_rules.yml"
      - "tests/test_fetcher_matrix.py"
      - "tests/debug_csv.py"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Copy whitelisted files
        run: |
          mkdir -p share
          cp -f src/vexto/scoring/http_client.py share/ || true
          cp -f src/vexto/scoring/website_fetchers.py share/ || true
          cp -f src/vexto/scoring/analyzer.py share/ || true
          cp -f src/vexto/scoring/_playwright_thread_fetcher.py share/ || true
          cp -f fetcher_diagnose_full.py share/ || true
          cp -f config/scoring_rules.yml share/ || true
          cp -f tests/test_fetcher_matrix.py share/ || true
          cp -f tests/debug_csv.py share/ || true

      - name: Build Gist payload JSON
        run: |
          python - << 'PY'
import json, os, glob
files = {}
for path in glob.glob("share/*"):
    name = os.path.basename(path)
    try:
        with open(path, "r", encoding="utf-8", errors="ignore") as f:
            content = f.read()
    except Exception:
        content = ""
    files[name] = {"content": content}
payload = {
    "files": files,
    "description": "Vexto debug snapshot (auto-update via GitHub Actions)"
}
with open("gist_payload.json", "w", encoding="utf-8") as f:
    json.dump(payload, f)
PY

      - name: Update Secret Gist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: |
          curl -sS -X PATCH \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/gists/$GIST_ID \
            -d @gist_payload.json
